# Generated by Django 3.2.13 on 2022-07-09 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='publish',
            new_name='created_on',
        ),
    ]
