# Generated by Django 3.2.13 on 2022-08-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='desc',
            field=models.TextField(default='This is my blog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(blank=True, default='static\\kola2.jpg', null=True, upload_to='media/image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default='My blog', max_length=200),
        ),
    ]
