# Generated by Django 3.2.13 on 2022-08-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20220803_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(blank=True, default='static/kola2.jpg', null=True, upload_to='media/image'),
        ),
    ]
